# Generated by Django 3.1.2 on 2020-10-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tables',
            old_name='table',
            new_name='post',
        ),
    ]
