# Generated by Django 3.1.2 on 2020-10-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20201017_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='x',
            field=models.CharField(default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='tables',
            name='y',
            field=models.CharField(default=1, max_length=1),
        ),
    ]
